name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - 'kubernetes/deployment.yaml'  
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "⚠️ No tests found"

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=my-project-key \
            -Dsonar.organization=my-org \
            -Dsonar.sources=./src \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}

      - name: Wait for SonarQube Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          echo "Checking SonarQube Quality Gate Status..."
          for i in {1..10}; do
            STATUS=$(curl -s -X GET "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=my-project-key" \
              -H "Authorization: Bearer ${SONAR_TOKEN}" | jq -r '.projectStatus.status')
            
            if [ "$STATUS" == "OK" ]; then
              echo "SonarQube Quality Gate PASSED!"
              exit 0
            elif [ "$STATUS" == "ERROR" ]; then
              echo "SonarQube Quality Gate FAILED!"
              exit 1
            else
              echo "SonarQube status: $STATUS. Retrying in 15 seconds... ($i/10)"
              sleep 15
            fi
          done
          echo " Timed out waiting for SonarQube Quality Gate."
          exit 1

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [sonar]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      image_tag: sha-${{ github.sha }}
    env:
      REGISTRY: docker.io
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | tr '/' '-')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}

  update-k8s:
    name: Update Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    env:
      IMAGE_TAG: sha-${{ github.sha }}
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | tr '/' '-')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Kubernetes deployment file
        run: |
          NEW_IMAGE="docker.io/${IMAGE_NAME}:${IMAGE_TAG}"
          sed -i "s|image: .*|image: ${NEW_IMAGE}|g" kubernetes/deployment.yaml
          echo "Updated deployment to use image: ${NEW_IMAGE}"
          cat kubernetes/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "MSR"
          git config --global user.email "msuryaprasad11@gmail.com"
          git add kubernetes/deployment.yaml
          git commit -m "Updated Kubernetes deployment with new image tag: $IMAGE_TAG [skip ci]" || echo "⚠️ No changes to commit"
          git push

  notify-success:
    name: Notify Slack on Success
    runs-on: ubuntu-latest
    needs: [update-k8s]
    if: success()
    steps:
      - name: Send success message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#36A64F"
          SLACK_MESSAGE: "CI/CD Pipeline completed successfully!"

  notify-failure:
    name: Notify Slack on Failure
    runs-on: ubuntu-latest
    needs: [test, sonar, build, docker, update-k8s]
    if: failure()  
    steps:
      - name: Send failure message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#FF0000"
          SLACK_MESSAGE: "CI/CD Pipeline Failed! Check logs for details."